[package]
name = "sttr"
version = "0.1.0"
authors = ["uncenter <uncenter@uncenter.dev>"]
license = "MIT"
description = "Easily change strings and convert string representations of data"
readme = "README.md"
homepage = "https://github.com/uncenter/sttr-rs"
repository = "https://github.com/uncenter/sttr-rs"
keywords = ["cli"]
categories = ["command-line-utilities"]
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
clap-stdin = "0.4.0"
convert_case = "0.6.0"
unicode-blocks = "0.1.9"

[lints.clippy]
all = "warn"
pedantic = "warn"
